# Generated by Django 5.2 on 2025-05-10 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('pn', models.CharField(max_length=50, unique=True, verbose_name='P/N')),
                ('sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='S/N')),
                ('acao', models.CharField(blank=True, choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=20, null=True, verbose_name='Ação')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('validade', models.CharField(choices=[('Não há', 'Não há'), ('2025-12-31', '31/12/2025'), ('2026-12-31', '31/12/2026'), ('2027-12-31', '31/12/2027')], default='Não há', max_length=50, verbose_name='Validade')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('nome_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável')),
                ('base', models.CharField(choices=[('Base Principal', 'Base Principal'), ('Base Porto Velho', 'Base Porto Velho'), ('Base Parintins', 'Base Parintins'), ('Base Santarém', 'Base Santarém'), ('Base Macapá', 'Base Macapá'), ('Base Marabá', 'Base Marabá'), ('Base Manaus', 'Base Manaus'), ('Sala 0316', 'Sala 0316'), ('Sala 2320', 'Sala 2320'), ('Sala 2322', 'Sala 2322')], default='Base Principal', max_length=50, verbose_name='Base')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('local_guardado', models.CharField(blank=True, max_length=100, verbose_name='Local onde está guardado')),
                ('destino', models.CharField(blank=True, max_length=100, verbose_name='Destino')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('pn', models.CharField(max_length=50, verbose_name='P/N')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado')], default='pendente', max_length=20, verbose_name='Status')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_processadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
