# Generated by Django 5.2 on 2025-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_produto_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='base_slug',
            field=models.SlugField(blank=True, editable=False, verbose_name='Slug da Base'),
        ),
    ]
