# Generated by Django 5.2 on 2025-05-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_base_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='base_slug',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
