# Generated by Django 5.2 on 2025-05-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_produto_base_slug_produto_estoque_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pn',
            field=models.CharField(max_length=50, verbose_name='P/N'),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('pn', 'base')},
        ),
    ]
