# Generated by Django 5.2 on 2025-05-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_produto_options_remove_produto_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='destino',
            field=models.CharField(blank=True, choices=[('Estoque', 'Estoque'), ('PS-ARB', 'PS-ARB'), ('PS-JOR', 'PS-JOR'), ('PS-VCB', 'PS-VCB'), ('PS-JJF', 'PS-JJF'), ('PS-ELI', 'PS-ELI'), ('PS-ALE', 'PS-ALE'), ('PS-JAE', 'PS-JAE'), ('PT-HYO', 'PT-HYO'), ('PP-JBB', 'PP-JBB'), ('PR-JJB', 'PR-JJB'), ('PT-YUN', 'PT-YUN'), ('PT-YTU', 'PT-YTU'), ('PP-JUL', 'PP-JUL')], max_length=100, null=True, verbose_name='Destino'),
        ),
    ]
