# Generated by Django 5.2 on 2025-05-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_produto_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomaterial',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destino'),
        ),
    ]
