# Generated by Django 5.2 on 2025-05-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_solicitacaomaterial_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomaterial',
            name='base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Base'),
        ),
    ]
